DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME varchar(255) NOT NULL,
	LAST_NAME varchar(255) NOT NULL,
	EMAIL varchar(255) NOT NULL,
	PHONE_NUMBER varchar(10) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	ROLE_ID INT NOT NULL,
	CONSTRAINT `FK_ROLES` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS ROLES;

CREATE TABLE ROLES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(255) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

INSERT INTO
	ROLES(NAME)
VALUES
	('admin');

INSERT INTO
	ROLES(NAME)
VALUES
	('user');